version: '3.6'
services:
  modbus-server:
    build:
      context: ./modbus_server
      dockerfile: ./Dockerfile
    networks:
      - ot
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - ot
    depends_on:
      - "influxdb"
      - "modbus-server"
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb/data:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=demouser
      - DOCKER_INFLUXDB_INIT_PASSWORD=demouser
      - DOCKER_INFLUXDB_INIT_ORG=factory 
      - DOCKER_INFLUXDB_INIT_BUCKET=modbus
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=edge
    networks:
      - ot
networks: 
  ot:
    name: ot