version: '3'
services:
  machines:
    build:
      context: .
      dockerfile: machine_simulator/dockerfile
    environment:
      - MACHINES=2
      - BROKER=mosquitto
    networks:
      - mqtt
    depends_on:
      - "mosquitto"
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - mqtt
    depends_on:
      - "mosquitto"
      - "influxdb"
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    networks:
      - mqtt
    volumes: 
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb/data:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=demouser
      - DOCKER_INFLUXDB_INIT_PASSWORD=demouser
      - DOCKER_INFLUXDB_INIT_ORG=MachineCo 
      - DOCKER_INFLUXDB_INIT_BUCKET=factory
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=edge
    networks:
      - mqtt
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=influxdata-flightsql-datasource
    volumes: 
      - grafana:/var/lib/grafana/
    networks:
      - mqtt
networks: 
  mqtt:
volumes:
  grafana: