version: '2.1'
services:
  generators:
    build:
      context: .
      dockerfile: generator_simulator/dockerfile
    environment:
      - GENERATORS=3
      - BROKER=mosquitto
    networks:
      - mqtt
    depends_on:
      - "mosquitto"
  telegraf:
    build:
      context: .
      dockerfile: telegraf/dockerfile
    networks:
      - mqtt
    depends_on:
      - "mosquitto"
      - "influxdb"
  mosquitto:
    build:
      context: .
      dockerfile: mosquitto/dockerfile
    ports:
      - 1883:1883
    networks:
      - mqtt
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=demouser
      - DOCKER_INFLUXDB_INIT_PASSWORD=demouser
      - DOCKER_INFLUXDB_INIT_ORG=influxroadshow 
      - DOCKER_INFLUXDB_INIT_BUCKET=generators
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=edge

    networks:
      - mqtt
networks: 
  mqtt:
volumes:
  influxdb:

