version: '3.6'
services:
  machines:
    image: machines:latest
    environment:
      - MACHINES=2
      - BROKER=mosquitto
    networks:
      - mqtt
    depends_on:
      - "mosquitto"
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/completed/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - mqtt
    depends_on:
      - "mosquitto"
      - "influxdb"
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    networks:
      - mqtt
    volumes: 
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb/data:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=demouser
      - DOCKER_INFLUXDB_INIT_PASSWORD=demouser
      - DOCKER_INFLUXDB_INIT_ORG=influxroadshow 
      - DOCKER_INFLUXDB_INIT_BUCKET=factory
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=edge
    networks:
      - mqtt
networks: 
  mqtt:
    name: mqtt
