{
 "title": "Fuel Generators",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Fuel Levels",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \n selector_last(fuel, time)['time'] AS time,\n selector_last(fuel, time)['value'] AS fuel,\n\"generatorID\",\n selector_last(lat, time)['value'] AS lat,\n selector_last(lon, time)['value'] AS lon\n\nFROM \"genData\" \nWHERE time >= $__timeFrom AND time <= $__timeTo\ngroup by 3"
    }
   ]
  },
  {
   "title": "Fuel Levels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, fuel, \"generatorID\"\nFROM \"genData\"\nWHERE time >= $__timeFrom AND time <= $__timeTo"
    }
   ]
  },
  {
   "title": "Generator 1 - Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "\n select \n selector_last(load, time)['value'] AS load\nFROM \"genData\" \nWHERE time >= $__timeFrom AND time <= $__timeTo AND \"generatorID\" = 'generator1'"
    }
   ]
  },
  {
   "title": "Generator 2 - Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": " select \n selector_last(load, time)['value'] AS load\nFROM \"genData\" \nWHERE time >= $__timeFrom AND time <= $__timeTo AND \"generatorID\" = 'generator2'"
    }
   ]
  },
  {
   "title": "Generator 3 - Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "\n select \n selector_last(load, time)['value'] AS load\nFROM \"genData\" \nWHERE  time >= $__timeFrom AND time <= $__timeTo AND \"generatorID\" = 'generator3'"
    }
   ]
  }
 ]
}