{
 "title": "Fuel Generators",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Fuel Levels",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "value": "fuel" }
     ],
     "queryText": "\n select \n selector_last(fuel, time)['time'] AS time,\n selector_last(fuel, time)['value'] AS fuel,\n\"generatorID\",\n selector_last(lat, time)['value'] AS lat,\nselector_last(lon, time)['value'] AS lon\nFROM \"genData\" \nWHERE  $__timeRange(time) \n group by 3\n\n\n\n ",
     "table": "\"genData\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Fuel Levels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "columns": [
      { "value": "fuel" }
     ],
     "queryText": " select $__dateBin(time),\n avg(fuel) as fuel,\n \"generatorID\"\n FROM \"genData\" \nWHERE  $__timeRange(time) \ngroup by 3, 1\norder by 1\n ",
     "table": "\"genData\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Generator 1 - Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "fuel" }
     ],
     "queryText": "\n select \n selector_last(load, time)['value'] AS load\nFROM \"genData\" \nWHERE  $__timeRange(time) AND \"generatorID\" = 'generator1'\n\n\n\n ",
     "table": "\"genData\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Generator 2 - Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "fuel" }
     ],
     "queryText": "\n select \n selector_last(load, time)['value'] AS load\nFROM \"genData\" \nWHERE  $__timeRange(time) AND \"generatorID\" = 'generator2'\n\n\n\n ",
     "table": "\"genData\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Generator 3 - Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "value": "fuel" }
     ],
     "queryText": "\n select \n selector_last(load, time)['value'] AS load\nFROM \"genData\" \nWHERE  $__timeRange(time) AND \"generatorID\" = 'generator3'\n\n\n\n ",
     "table": "\"genData\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  }
 ]
}